version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: fastapi_app
    ports:
      - "${FASTAPI_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/src
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.devcontainer/init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh

volumes:
  postgres_data: